/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheNavbar: typeof import('./components/TheNavbar.vue')['default']
    VBlogCard: typeof import('./components/VBlogCard.vue')['default']
    VIconButton: typeof import('./components/VIconButton.vue')['default']
    VIconCard: typeof import('./components/VIconCard.vue')['default']
  }
}
